name: Build (macOS 12, Xcode 13.4.1)

on:
  push:
    branches:
      - 'main'
      - 'chore/**'
      - 'docs/**'
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - 'refactor/**'
      - 'releases/**'
      - 'style/**'
      - 'test/**'
      - 'tech/**'

env:
  BINARIES_PATH: .Resources

jobs:
  build:
    name: Prepare libpact_ffi binaries
    runs-on: macos-12
    timeout-minutes: 60

    concurrency:
      group: build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: "ðŸ“¦ Cache binaries"
        uses: actions/cache@v3
        with:
          path: ${{ env.BINARIES_PATH }}
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Use Xcode 13.4.1
        run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app

      - name: Prepare binaries
        run: |
          Support/build_rust_dependencies

  test:
    name: Run tests
    runs-on: macos11
    needs: [build]

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwiftMockServer-iOS"
            destination: "platform=iOS Simulator,name=iPhone 13 Pro"
          - scheme: "PactSwiftMockServer-macOS"
            destination: "arch=x86_64"

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    concurrency:
      group: test-${{ github.ref }}-${{ matrix.scheme }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: Prepare Tools
        run: |
          Support/prepare_build_tools

      - name: Run tests (Xcode)
        run: |
          ./Support/build_test

      - name: Upload code coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -J 'PactSwiftMockServer'

  # after_success:
  #   name: Build PactSwift
  #   needs: [test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Build demo projects
  #       run: |
  #         curl -X POST https://api.github.com/repos/surpher/PactSwift/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.PACT_SWIFT_TOKEN }} --data '{"event_type":"PactSwiftMockServer - ${{ github.event.head_commit.message }}"}'
