name: Build

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - scheme: "PactSwiftMockServer_iOS"
            destination: "platform=iOS Simulator,name=iPhone 12 Pro"
          - scheme: "PactSwiftMockServer_macOS"
            destination: "arch=x86_64"

    env:
      SCHEME: ${{ matrix.scheme }}
      DESTINATION: ${{ matrix.destination }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: Prepare Tools
        run: |
          Support/prepare_build_tools

      - name: Run tests (Xcode)
        run: |
          set -o pipefail && xcodebuild clean test -project PactSwiftMockServer.xcodeproj -scheme "$SCHEME" -destination "$DESTINATION" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcbeautify

      - name: Upload code coverage
        run: |
          bash <(curl -s https://codecov.io/bash) -J 'PactSwiftMockServer'

  test_carthage:
    needs: [test]
    name: Test Carthage
    runs-on: macOS-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "ios"
          - platform: "macos"

    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app

      # - name: Test Carthage Compatibility
      #   run: |
      #     echo "âš ï¸ Running 'carthage build' with a Xcode 12 workaround script - https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323"
      #     ./Support/carthage_xcode12 build --no-skip-current --platform "$PLATFORM"

  test_spm:
    name: Swift CLI build and test (SPM)
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Use Xcode 12.2
        run: sudo xcode-select -switch /Applications/Xcode_12.2.app

      - name: Prepare Tools
        run: |
          Support/prepare_build_tools

      - name: Build binary && swift test
        run: |
          echo "ðŸ‘·â€â™€ï¸ running 'swift build -c debug'"
          set -o pipefail && swift build -c debug | xcbeautify
          echo "ðŸ§ª running 'swift test'"
          set -o pipefail && swift test -Xlinker -LResources/x86_64-darwin | xcbeautify

  # after_success:
  #   name: Build PactSwift
  #   needs: [test, test_carthage, test_spm]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Build demo projects
  #       run: |
  #         curl -X POST https://api.github.com/repos/surpher/PactSwift/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.PACT_SWIFT_TOKEN }} --data '{"event_type":"PactSwiftMockServer - ${{ github.event.head_commit.message }}"}'
